### ISSUE TITLE
HM-CC-RT-DN does not expose WEATHER_RECEIVER

### ISSUE THREAD

**Issue by iimehl** [Homegear/Homegear-HomeMaticBidCoS#16]
According to page 28 on https://www.eq-3.de/Downloads/eq3/download%20bereich/hm_web_ui_doku/HM-Script_4-Datenpunkte.pdf
the HM-CC-RT-DN thermostat has an input option WEATHER_RECEIVER on channel 1.
This input allows to feed temperature measurements to the thermostat as control input, e.g. from the other side of the room. Unfortunately this value is not exposed. 

I know the document says  "Kanaltyp WEATHER_RECEIVER Der Kanal besitzt keine Datenpunkte."  but it says the same for WINDOW_SWITCH_RECEIVER which is exposed by homegear and working fine in openhab.

System:
Openhab Snapshot 2.5 (#1759)
Raspberry PI
Homegear version 0.8.0-2820

**Comment by hfedcba** [comment]
The Window-Switch-Receiver works, because it is explicitly implemented by simulating a window contact. For the WEATHER_RECEIVER the same would have to be done. At the moment, we don't have time in our team to implement this feature. But I'm happy to help anybody who wants to implement this feature in the source code.
